### ISSUE TITLE
Some Blocks No Longer Hidden

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/block-blocks#2]
Seeing discrepancies between the removeBlocks array and the blocks appearing within the interface. 

Eg: reverbnation, smugmug, wordpress.tv, reddit, meetup.com etc. 

![2021-05-11_18-50-24](https://user-images.githubusercontent.com/480667/117894354-2d4a3100-b28a-11eb-890a-6cf10340889a.png)

**Comment by r-a-y** [comment]
WordPress 5.4.0 changed how the core `Embed` block is rendered. All core embed blocks are now block variants: https://make.wordpress.org/core/2020/02/27/introduce-block-variations-api/

I've updated the code to account for that.

**Comment by mrjarbenne** [comment]
Thanks for that. We are back in business.
